### ISSUE TITLE
App breaking down when launched on Streamlit. 

### ISSUE THREAD

**Issue by AlexPam** [OpenDataforWeb3/Mirall0x#22]
The app breaks down after running the Streamlit run command. 
```
streamlit run main\\main\\mirall0x.py
```
I am unsure of where the error is coming from but would be glad to fix. 
Please preview @stefi-says  so I will be sure the error is not from my end alone.

<img width="941" alt="Screenshot 2023-07-12 at 22 22 26" src="https://github.com/OpenDataforWeb3/Mirall0x/assets/55463668/f28f318b-a742-4ef2-86e7-f12af50c3c3d">

**Comment by stefi-says** [comment]
Hey @AlexPam thanks for testing out! Yeha, its breaking because it have been modified for deploy and its making a call for the   api secrets that are insiede the streamlit server, to run it locally you should change this part to the proper api keys : 
![image](https://github.com/OpenDataforWeb3/Mirall0x/assets/25551810/a080d428-e900-46c0-aa4e-5d343e9e41ae)

so you need a github personal authentication token and a covalent api key. both of them you can get for free. 
Im thinking that probably we should have some documentation mentining the diference between running it locally and deploying on streamlit . by the way , if you just want to use it, it live here: https://mirall0x.streamlit.app/ 
What your thoughts about it? 
Thanks again

**Comment by AlexPam** [comment]
Alright @stefi-says  I was able to to run the app locally and it was successful. Would send a PR on the documentation on running it locally.

**Comment by stefi-says** [comment]
solved by @AlexPam  on  #23
